apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: gateway-ns
data:
  PRODUCT_GRPC_ADDR:  "product-svc.backend-ns.svc.cluster.local:50051"
  AUTH_GRPC_ADDR:     "auth-member-svc.backend-ns.svc.cluster.local:50052"
  PAYMENT_GRPC_ADDR:  "payment-svc.backend-ns.svc.cluster.local:50053"
  REDIS_WRITE_URL:    "redis://:k8spass%23@redis-svc-master.redis-ns.svc.cluster.local:6379/0"
  REDIS_READ_URL:     "redis://:k8spass%23@redis-svc-follower.redis-ns.svc.cluster.local:6379/0"
  MONGODB_DB:         "ecommerce"
  CORS_ORIGINS:       "http://frontend-svc.frontend-ns.svc.cluster.local"
  TZ:                 "Asia/Seoul"
