apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: gateway-ns
type: Opaque
stringData:
  JWT_SECRET:   "CHANGE_ME"
  MONGODB_URI:  "mongodb://admin:CHANGE_ME@mongodb-svc.mongodb-ns.svc.cluster.local:27017/?authSource=admin&readPreference=secondaryPreferred"
