apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis-ns
type: Opaque
stringData:
  password: "k8spass#"
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: redis-svc
  namespace: redis-ns
spec:
  clusterSize: 3
  kubernetesConfig:
    image: 192.168.0.54/ecommerce/redis:7.0
    redisSecret:
      name: redis-secret
      key: password
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
