apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: backend-ns
type: Opaque
stringData:
  MONGODB_URI: "mongodb://kevin:k8spass%23@mongodb-svc.mongodb-ns.svc.cluster.local:27017/?authSource=ecommerce&readPreference=secondaryPreferred"
