apiVersion: v1
kind: ConfigMap
metadata:
  name: crawler-best-config
data:
  CRAWL_TARGET: "best"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crawler-sales-config
data:
  CRAWL_TARGET: "sales"
