apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "kafka-svc:9092"
  KAFKA_PRODUCT_TOPIC: "crawled-products"
  KAFKA_CONSUMER_GROUP: "product-loader"

  # MongoDB
  MONGODB_DB: "ecommerce"

  # Redis
  REDIS_URL: "redis://redis-svc:6379/0"
  CACHE_TTL_SECONDS: "300"

  # gRPC 서비스 주소
  PRODUCT_GRPC_ADDR: "product-svc:50051"
  AUTH_GRPC_ADDR: "auth-member-svc:50052"
  PAYMENT_GRPC_ADDR: "payment-svc:50053"

  # gRPC 서버 포트 (각 서비스 내부용)
  PRODUCT_GRPC_PORT: "50051"
  AUTH_GRPC_PORT: "50052"
  PAYMENT_GRPC_PORT: "50053"

  # Gateway
  CORS_ORIGINS: "http://frontend-svc"

  # MariaDB
  MARIADB_HOST: "mariadb-svc"
  MARIADB_USER: "root"
  MARIADB_DB: "ecommerce"
