# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"0\n\x08\x43\x61rtItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"X\n\x0f\x43heckoutRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12 \n\x05items\x18\x02 \x03(\x0b\x32\x11.payment.CartItem\x12\x12\n\naddress_id\x18\x03 \x01(\x05\"n\n\x10\x43heckoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x14\n\x0cpoints_after\x18\x04 \x01(\x05\x12\x13\n\x0bitems_count\x18\x05 \x01(\x05\"7\n\x12\x43\x61ncelOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"N\n\x13\x43\x61ncelOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rrefund_amount\x18\x03 \x01(\x05\x32\x9b\x01\n\x0ePaymentService\x12?\n\x08\x43heckout\x12\x18.payment.CheckoutRequest\x1a\x19.payment.CheckoutResponse\x12H\n\x0b\x43\x61ncelOrder\x12\x1b.payment.CancelOrderRequest\x1a\x1c.payment.CancelOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTITEM']._serialized_start=26
  _globals['_CARTITEM']._serialized_end=74
  _globals['_CHECKOUTREQUEST']._serialized_start=76
  _globals['_CHECKOUTREQUEST']._serialized_end=164
  _globals['_CHECKOUTRESPONSE']._serialized_start=166
  _globals['_CHECKOUTRESPONSE']._serialized_end=276
  _globals['_CANCELORDERREQUEST']._serialized_start=278
  _globals['_CANCELORDERREQUEST']._serialized_end=333
  _globals['_CANCELORDERRESPONSE']._serialized_start=335
  _globals['_CANCELORDERRESPONSE']._serialized_end=413
  _globals['_PAYMENTSERVICE']._serialized_start=416
  _globals['_PAYMENTSERVICE']._serialized_end=571
# @@protoc_insertion_point(module_scope)
