apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: backend-ns
data:
  AUTH_GRPC_ADDR:    "auth-member-svc.backend-ns.svc.cluster.local:50052"
  PRODUCT_GRPC_ADDR: "product-svc.backend-ns.svc.cluster.local:50051"
  PAYMENT_GRPC_PORT: "50053"
