# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/auth.AuthService/Register',
                request_serializer=auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=auth__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/auth.AuthService/Login',
                request_serializer=auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.GetMe = channel.unary_unary(
                '/auth.AuthService/GetMe',
                request_serializer=auth__pb2.GetMeRequest.SerializeToString,
                response_deserializer=auth__pb2.GetMeResponse.FromString,
                _registered_method=True)
        self.GetPoints = channel.unary_unary(
                '/auth.AuthService/GetPoints',
                request_serializer=auth__pb2.GetPointsRequest.SerializeToString,
                response_deserializer=auth__pb2.GetPointsResponse.FromString,
                _registered_method=True)
        self.SpendPoints = channel.unary_unary(
                '/auth.AuthService/SpendPoints',
                request_serializer=auth__pb2.SpendPointsRequest.SerializeToString,
                response_deserializer=auth__pb2.SpendPointsResponse.FromString,
                _registered_method=True)
        self.RefundPoints = channel.unary_unary(
                '/auth.AuthService/RefundPoints',
                request_serializer=auth__pb2.RefundPointsRequest.SerializeToString,
                response_deserializer=auth__pb2.RefundPointsResponse.FromString,
                _registered_method=True)
        self.AddAddress = channel.unary_unary(
                '/auth.AuthService/AddAddress',
                request_serializer=auth__pb2.AddAddressRequest.SerializeToString,
                response_deserializer=auth__pb2.AddAddressResponse.FromString,
                _registered_method=True)
        self.GetAddresses = channel.unary_unary(
                '/auth.AuthService/GetAddresses',
                request_serializer=auth__pb2.GetAddressesRequest.SerializeToString,
                response_deserializer=auth__pb2.GetAddressesResponse.FromString,
                _registered_method=True)
        self.SetDefaultAddress = channel.unary_unary(
                '/auth.AuthService/SetDefaultAddress',
                request_serializer=auth__pb2.SetDefaultAddressRequest.SerializeToString,
                response_deserializer=auth__pb2.SetDefaultAddressResponse.FromString,
                _registered_method=True)
        self.DeleteAddress = channel.unary_unary(
                '/auth.AuthService/DeleteAddress',
                request_serializer=auth__pb2.DeleteAddressRequest.SerializeToString,
                response_deserializer=auth__pb2.DeleteAddressResponse.FromString,
                _registered_method=True)
        self.CreateOrder = channel.unary_unary(
                '/auth.AuthService/CreateOrder',
                request_serializer=auth__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateOrderResponse.FromString,
                _registered_method=True)
        self.GetOrders = channel.unary_unary(
                '/auth.AuthService/GetOrders',
                request_serializer=auth__pb2.GetOrdersRequest.SerializeToString,
                response_deserializer=auth__pb2.GetOrdersResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/auth.AuthService/CancelOrder',
                request_serializer=auth__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=auth__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.WithdrawUser = channel.unary_unary(
                '/auth.AuthService/WithdrawUser',
                request_serializer=auth__pb2.WithdrawUserRequest.SerializeToString,
                response_deserializer=auth__pb2.WithdrawUserResponse.FromString,
                _registered_method=True)
        self.AdminListUsers = channel.unary_unary(
                '/auth.AuthService/AdminListUsers',
                request_serializer=auth__pb2.AdminListUsersRequest.SerializeToString,
                response_deserializer=auth__pb2.AdminListUsersResponse.FromString,
                _registered_method=True)
        self.AdminDeleteUser = channel.unary_unary(
                '/auth.AuthService/AdminDeleteUser',
                request_serializer=auth__pb2.AdminDeleteUserRequest.SerializeToString,
                response_deserializer=auth__pb2.AdminDeleteUserResponse.FromString,
                _registered_method=True)
        self.AdminRestoreUser = channel.unary_unary(
                '/auth.AuthService/AdminRestoreUser',
                request_serializer=auth__pb2.AdminRestoreUserRequest.SerializeToString,
                response_deserializer=auth__pb2.AdminRestoreUserResponse.FromString,
                _registered_method=True)
        self.AdminAdjustPoints = channel.unary_unary(
                '/auth.AuthService/AdminAdjustPoints',
                request_serializer=auth__pb2.AdminAdjustPointsRequest.SerializeToString,
                response_deserializer=auth__pb2.AdminAdjustPointsResponse.FromString,
                _registered_method=True)
        self.AdminSetAdmin = channel.unary_unary(
                '/auth.AuthService/AdminSetAdmin',
                request_serializer=auth__pb2.AdminSetAdminRequest.SerializeToString,
                response_deserializer=auth__pb2.AdminSetAdminResponse.FromString,
                _registered_method=True)
        self.AdminGetAllOrders = channel.unary_unary(
                '/auth.AuthService/AdminGetAllOrders',
                request_serializer=auth__pb2.AdminGetAllOrdersRequest.SerializeToString,
                response_deserializer=auth__pb2.AdminGetAllOrdersResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """인증
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoints(self, request, context):
        """포인트
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpendPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefundPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAddress(self, request, context):
        """배송지
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddresses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrder(self, request, context):
        """주문
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WithdrawUser(self, request, context):
        """회원 탈퇴
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminListUsers(self, request, context):
        """관리자
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminDeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminRestoreUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminAdjustPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminSetAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminGetAllOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=auth__pb2.RegisterRequest.FromString,
                    response_serializer=auth__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auth__pb2.LoginRequest.FromString,
                    response_serializer=auth__pb2.LoginResponse.SerializeToString,
            ),
            'GetMe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMe,
                    request_deserializer=auth__pb2.GetMeRequest.FromString,
                    response_serializer=auth__pb2.GetMeResponse.SerializeToString,
            ),
            'GetPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoints,
                    request_deserializer=auth__pb2.GetPointsRequest.FromString,
                    response_serializer=auth__pb2.GetPointsResponse.SerializeToString,
            ),
            'SpendPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.SpendPoints,
                    request_deserializer=auth__pb2.SpendPointsRequest.FromString,
                    response_serializer=auth__pb2.SpendPointsResponse.SerializeToString,
            ),
            'RefundPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundPoints,
                    request_deserializer=auth__pb2.RefundPointsRequest.FromString,
                    response_serializer=auth__pb2.RefundPointsResponse.SerializeToString,
            ),
            'AddAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAddress,
                    request_deserializer=auth__pb2.AddAddressRequest.FromString,
                    response_serializer=auth__pb2.AddAddressResponse.SerializeToString,
            ),
            'GetAddresses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddresses,
                    request_deserializer=auth__pb2.GetAddressesRequest.FromString,
                    response_serializer=auth__pb2.GetAddressesResponse.SerializeToString,
            ),
            'SetDefaultAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultAddress,
                    request_deserializer=auth__pb2.SetDefaultAddressRequest.FromString,
                    response_serializer=auth__pb2.SetDefaultAddressResponse.SerializeToString,
            ),
            'DeleteAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAddress,
                    request_deserializer=auth__pb2.DeleteAddressRequest.FromString,
                    response_serializer=auth__pb2.DeleteAddressResponse.SerializeToString,
            ),
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=auth__pb2.CreateOrderRequest.FromString,
                    response_serializer=auth__pb2.CreateOrderResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=auth__pb2.GetOrdersRequest.FromString,
                    response_serializer=auth__pb2.GetOrdersResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=auth__pb2.CancelOrderRequest.FromString,
                    response_serializer=auth__pb2.CancelOrderResponse.SerializeToString,
            ),
            'WithdrawUser': grpc.unary_unary_rpc_method_handler(
                    servicer.WithdrawUser,
                    request_deserializer=auth__pb2.WithdrawUserRequest.FromString,
                    response_serializer=auth__pb2.WithdrawUserResponse.SerializeToString,
            ),
            'AdminListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminListUsers,
                    request_deserializer=auth__pb2.AdminListUsersRequest.FromString,
                    response_serializer=auth__pb2.AdminListUsersResponse.SerializeToString,
            ),
            'AdminDeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminDeleteUser,
                    request_deserializer=auth__pb2.AdminDeleteUserRequest.FromString,
                    response_serializer=auth__pb2.AdminDeleteUserResponse.SerializeToString,
            ),
            'AdminRestoreUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminRestoreUser,
                    request_deserializer=auth__pb2.AdminRestoreUserRequest.FromString,
                    response_serializer=auth__pb2.AdminRestoreUserResponse.SerializeToString,
            ),
            'AdminAdjustPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminAdjustPoints,
                    request_deserializer=auth__pb2.AdminAdjustPointsRequest.FromString,
                    response_serializer=auth__pb2.AdminAdjustPointsResponse.SerializeToString,
            ),
            'AdminSetAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminSetAdmin,
                    request_deserializer=auth__pb2.AdminSetAdminRequest.FromString,
                    response_serializer=auth__pb2.AdminSetAdminResponse.SerializeToString,
            ),
            'AdminGetAllOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminGetAllOrders,
                    request_deserializer=auth__pb2.AdminGetAllOrdersRequest.FromString,
                    response_serializer=auth__pb2.AdminGetAllOrdersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/Register',
            auth__pb2.RegisterRequest.SerializeToString,
            auth__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/Login',
            auth__pb2.LoginRequest.SerializeToString,
            auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetMe',
            auth__pb2.GetMeRequest.SerializeToString,
            auth__pb2.GetMeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetPoints',
            auth__pb2.GetPointsRequest.SerializeToString,
            auth__pb2.GetPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpendPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/SpendPoints',
            auth__pb2.SpendPointsRequest.SerializeToString,
            auth__pb2.SpendPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefundPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RefundPoints',
            auth__pb2.RefundPointsRequest.SerializeToString,
            auth__pb2.RefundPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AddAddress',
            auth__pb2.AddAddressRequest.SerializeToString,
            auth__pb2.AddAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddresses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetAddresses',
            auth__pb2.GetAddressesRequest.SerializeToString,
            auth__pb2.GetAddressesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/SetDefaultAddress',
            auth__pb2.SetDefaultAddressRequest.SerializeToString,
            auth__pb2.SetDefaultAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteAddress',
            auth__pb2.DeleteAddressRequest.SerializeToString,
            auth__pb2.DeleteAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateOrder',
            auth__pb2.CreateOrderRequest.SerializeToString,
            auth__pb2.CreateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetOrders',
            auth__pb2.GetOrdersRequest.SerializeToString,
            auth__pb2.GetOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CancelOrder',
            auth__pb2.CancelOrderRequest.SerializeToString,
            auth__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WithdrawUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/WithdrawUser',
            auth__pb2.WithdrawUserRequest.SerializeToString,
            auth__pb2.WithdrawUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AdminListUsers',
            auth__pb2.AdminListUsersRequest.SerializeToString,
            auth__pb2.AdminListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminDeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AdminDeleteUser',
            auth__pb2.AdminDeleteUserRequest.SerializeToString,
            auth__pb2.AdminDeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminRestoreUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AdminRestoreUser',
            auth__pb2.AdminRestoreUserRequest.SerializeToString,
            auth__pb2.AdminRestoreUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminAdjustPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AdminAdjustPoints',
            auth__pb2.AdminAdjustPointsRequest.SerializeToString,
            auth__pb2.AdminAdjustPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminSetAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AdminSetAdmin',
            auth__pb2.AdminSetAdminRequest.SerializeToString,
            auth__pb2.AdminSetAdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminGetAllOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AdminGetAllOrders',
            auth__pb2.AdminGetAllOrdersRequest.SerializeToString,
            auth__pb2.AdminGetAllOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
